@extends('admin.layouts.app')
@section('title', 'Service Plans')
@section('page_title', 'Service Plans')
@section('content')
<section class="mb-8 overflow-hidden rounded-xl bg-teal-950 px-5 py-6 shadow-[0_14px_32px_rgba(15,60,58,0.14)] sm:px-7 sm:py-7"><p class="text-sm font-medium text-teal-300">Customer retention</p><h1 class="mt-2 text-2xl font-semibold tracking-tight text-white sm:text-3xl">Recurring service plans</h1><p class="mt-2 max-w-2xl text-sm leading-6 text-teal-50/85">Monitor opt-in maintenance reminders. Plans notify customers; they still choose whether to create a new booking.</p></section>
<div class="mb-6 grid gap-4 sm:grid-cols-2"><div class="rounded-xl border border-slate-200 bg-white p-5"><p class="text-sm text-slate-500">Active plans</p><p class="mt-2 text-3xl font-semibold text-slate-950">{{ $metrics['active'] }}</p></div><div class="rounded-xl border border-amber-100 bg-amber-50 p-5"><p class="text-sm text-amber-800">Due for reminder</p><p class="mt-2 text-3xl font-semibold text-amber-900">{{ $metrics['due'] }}</p></div></div>
<form method="GET" class="mb-6 rounded-xl border border-teal-100 bg-teal-50/40 p-5"><div class="grid gap-4 md:grid-cols-2"><input type="search" name="search" value="{{ request('search') }}" placeholder="Customer or service" class="h-11 rounded-lg border-teal-200 bg-white px-4 text-sm"><select name="active" class="h-11 rounded-lg border-teal-200 bg-white px-4 text-sm"><option value="">All plans</option><option value="1" @selected(request('active')==='1')>Active</option><option value="0" @selected(request('active')==='0')>Paused</option></select></div><button class="mt-4 rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white">Apply filters</button></form>
<div class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-sm"><thead class="bg-teal-950 text-left text-xs font-semibold text-teal-50"><tr><th class="px-6 py-3.5">Customer</th><th class="px-6 py-3.5">Service</th><th class="px-6 py-3.5">Cycle</th><th class="px-6 py-3.5">Next reminder</th><th class="px-6 py-3.5">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($plans as $plan)<tr><td class="px-6 py-4"><p class="font-semibold text-slate-900">{{ $plan->customer?->name }}</p><p class="text-xs text-slate-500">{{ $plan->customer?->email }}</p></td><td class="px-6 py-4 font-semibold text-slate-900">{{ $plan->service_name }}</td><td class="px-6 py-4 text-slate-600">Every {{ $plan->interval_days }} days<br><span class="text-xs">{{ $plan->reminder_days_before }} days early</span></td><td class="px-6 py-4 text-slate-600">{{ $plan->next_reminder_at?->format('d M Y, h:i A') }}</td><td class="px-6 py-4"><span class="rounded-full px-3 py-1 text-xs font-medium {{ $plan->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $plan->is_active ? 'ACTIVE' : 'PAUSED' }}</span></td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-slate-500">No recurring service plans match these filters.</td></tr>@endforelse</tbody></table></div>@if($plans->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $plans->links() }}</div>@endif</div>
@endsection
